auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title
categories: [Technology, Thinking, Arts, Science, Fitness]
excerpt_separator: "<!--more-->"
destination: _site
url: http://127.0.0.1:4000
plugins:
 - jemoji
css_flavour: standard
